######################################################################
# Automatically generated by qmake (2.01a) Thu Nov 5 21:45:54 2009
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

CONFIG += qt x11

unix:LIBS += -lXtst

QT += network

# Input
HEADERS += InputListener.h VideoStreamer.h
SOURCES += InputListener.cpp VideoStreamer.cpp main.cpp
