######################################################################
# Automatically generated by qmake (2.01a) Thu Nov 5 21:45:54 2009
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

QT += network
QT += X11Info

# Input
HEADERS += listener.h
SOURCES += listener.cpp main.cpp
